# Base de Datos Pokemon
POKEMON_DB = [
    {"id":1,"nombre":"Dragapult","tipo1":"Dragon","tipo2":"Fantasma","hp":88,"atk":120,"def_":75,"spe":142,
     "movimientos":[
        {"nombre":"Dardos Dragon","tipo":"Dragon","categoria":"Fisico","poder":50,"precision":0.9,"efecto":"Golpea 2 veces","pp":10,"ppMax":10},
        {"nombre":"Cometa Draco","tipo":"Dragon","categoria":"Especial","poder":130,"precision":0.9,"efecto":"Baja mucho At. Especial","pp":5,"ppMax":5},
        {"nombre":"Bola Sombra","tipo":"Fantasma","categoria":"Especial","poder":80,"precision":1.0,"efecto":"20% bajar Def. Especial","pp":15,"ppMax":15},
        {"nombre":"Ida y Vuelta","tipo":"Bicho","categoria":"Fisico","poder":70,"precision":1.0,"efecto":"Cambia al usuario","pp":20,"ppMax":20},
        {"nombre":"Lanzallamas","tipo":"Fuego","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% quemar","pp":15,"ppMax":15},
        {"nombre":"Rayo","tipo":"Electrico","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% paralizar","pp":15,"ppMax":15},
        {"nombre":"Fuego Fatuo","tipo":"Fuego","categoria":"Estado","poder":0,"precision":0.85,"efecto":"Quema al rival","pp":15,"ppMax":15},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10}
    ]},
    {"id":2,"nombre":"Garchomp","tipo1":"Dragon","tipo2":"Tierra","hp":108,"atk":130,"def_":95,"spe":102,
     "movimientos":[
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Garra Dragon","tipo":"Dragon","categoria":"Fisico","poder":80,"precision":1.0,"efecto":"Sin efecto adicional","pp":15,"ppMax":15},
        {"nombre":"Trampa Rocas","tipo":"Roca","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Daño al cambiar rival","pp":20,"ppMax":20},
        {"nombre":"Danza Espada","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+2 Ataque Fisico","pp":20,"ppMax":20},
        {"nombre":"Roca Afilada","tipo":"Roca","categoria":"Fisico","poder":100,"precision":0.8,"efecto":"Alto indice critico","pp":5,"ppMax":5},
        {"nombre":"Colmillo Ignígero","tipo":"Fuego","categoria":"Fisico","poder":65,"precision":0.95,"efecto":"10% quemar o retroceso","pp":10,"ppMax":10},
        {"nombre":"Toxico","tipo":"Veneno","categoria":"Estado","poder":0,"precision":0.9,"efecto":"Veneno grave","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10}
    ]},
    {"id":3,"nombre":"Mew","tipo1":"Psiquico","tipo2":None,"hp":100,"atk":100,"def_":100,"spe":100,
     "movimientos":[
        {"nombre":"Nieve Polvo","tipo":"Psiquico","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% congelar","pp":10,"ppMax":10},
        {"nombre":"Llamarada","tipo":"Fuego","categoria":"Especial","poder":110,"precision":0.85,"efecto":"10% quemar","pp":5,"ppMax":5},
        {"nombre":"Rayo Hielo","tipo":"Hielo","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% congelar","pp":10,"ppMax":10},
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Onda Trueno","tipo":"Electrico","categoria":"Estado","poder":0,"precision":0.9,"efecto":"Paraliza al rival","pp":20,"ppMax":20},
        {"nombre":"Recuperacion","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Recupera 50% HP","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Mofa","tipo":"Siniestro","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Bloquea movimientos de estado","pp":20,"ppMax":20}
    ]},
    {"id":4,"nombre":"Rayquaza","tipo1":"Dragon","tipo2":"Volador","hp":105,"atk":150,"def_":90,"spe":95,
     "movimientos":[
        {"nombre":"Enfado","tipo":"Dragon","categoria":"Fisico","poder":120,"precision":1.0,"efecto":"2-3 turnos luego confunde","pp":10,"ppMax":10},
        {"nombre":"Cometa Draco","tipo":"Dragon","categoria":"Especial","poder":130,"precision":0.9,"efecto":"Baja mucho At. Especial","pp":5,"ppMax":5},
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Llamarada","tipo":"Fuego","categoria":"Especial","poder":110,"precision":0.85,"efecto":"10% quemar","pp":5,"ppMax":5},
        {"nombre":"Danza Dragon","tipo":"Dragon","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+1 Ataque y +1 Velocidad","pp":10,"ppMax":10},
        {"nombre":"Vuelo","tipo":"Volador","categoria":"Fisico","poder":90,"precision":0.95,"efecto":"Vuelo","pp":15,"ppMax":15},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Respiro","tipo":"Volador","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Recupera 50% HP","pp":10,"ppMax":10}
    ]},
    {"id":5,"nombre":"Swampert","tipo1":"Agua","tipo2":"Tierra","hp":100,"atk":110,"def_":90,"spe":60,
     "movimientos":[
        {"nombre":"Cascada","tipo":"Agua","categoria":"Fisico","poder":80,"precision":1.0,"efecto":"20% retroceso","pp":15,"ppMax":15},
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Trampa Rocas","tipo":"Roca","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Daño al cambiar rival","pp":20,"ppMax":20},
        {"nombre":"Avalancha","tipo":"Hielo","categoria":"Fisico","poder":60,"precision":1.0,"efecto":"30% retroceso","pp":10,"ppMax":10},
        {"nombre":"Abocajarro","tipo":"Lucha","categoria":"Fisico","poder":85,"precision":1.0,"efecto":"10% bajar Defensa","pp":15,"ppMax":15},
        {"nombre":"Toxico","tipo":"Veneno","categoria":"Estado","poder":0,"precision":0.9,"efecto":"Veneno grave","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Mofa","tipo":"Siniestro","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Bloquea movimientos de estado","pp":20,"ppMax":20}
    ]},
    {"id":6,"nombre":"Tyranitar","tipo1":"Roca","tipo2":"Siniestro","hp":100,"atk":134,"def_":110,"spe":61,
     "movimientos":[
        {"nombre":"Roca Afilada","tipo":"Roca","categoria":"Fisico","poder":100,"precision":0.8,"efecto":"Alto indice critico","pp":5,"ppMax":5},
        {"nombre":"Triturar","tipo":"Siniestro","categoria":"Fisico","poder":80,"precision":1.0,"efecto":"30% bajar Defensa","pp":15,"ppMax":15},
        {"nombre":"Trampa Rocas","tipo":"Roca","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Daño al cambiar rival","pp":20,"ppMax":20},
        {"nombre":"Danza Dragon","tipo":"Dragon","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+1 Ataque y +1 Velocidad","pp":10,"ppMax":10},
        {"nombre":"Puño Fuego","tipo":"Fuego","categoria":"Fisico","poder":75,"precision":1.0,"efecto":"10% quemar","pp":10,"ppMax":10},
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Puño Hielo","tipo":"Hielo","categoria":"Fisico","poder":75,"precision":1.0,"efecto":"10% congelar","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10}
    ]},
    {"id":7,"nombre":"Blaziken","tipo1":"Fuego","tipo2":"Lucha","hp":80,"atk":120,"def_":70,"spe":80,
     "movimientos":[
        {"nombre":"Pirotecnia","tipo":"Fuego","categoria":"Fisico","poder":120,"precision":0.85,"efecto":"Quema por 2-3 turnos","pp":15,"ppMax":15},
        {"nombre":"Super Puño","tipo":"Lucha","categoria":"Fisico","poder":40,"precision":1.0,"efecto":"Prioridad +1","pp":10,"ppMax":10},
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Acrobata","tipo":"Volador","categoria":"Fisico","poder":55,"precision":1.0,"efecto":"Daño x2 si tiene estado","pp":15,"ppMax":15},
        {"nombre":"Danza Espada","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+2 Ataque Fisico","pp":20,"ppMax":20},
        {"nombre":"Impulso","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+1 Velocidad","pp":30,"ppMax":30},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Proteccion","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Proteccion","pp":10,"ppMax":10}
    ]},
    {"id":8,"nombre":"Corviknight","tipo1":"Volador","tipo2":"Acero","hp":98,"atk":87,"def_":105,"spe":67,
     "movimientos":[
        {"nombre":"Pajaro Osado","tipo":"Volador","categoria":"Fisico","poder":120,"precision":1.0,"efecto":"Usuario recibe 1/3 del daño","pp":15,"ppMax":15},
        {"nombre":"Respiro","tipo":"Volador","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Recupera 50% HP","pp":10,"ppMax":10},
        {"nombre":"Despejar","tipo":"Volador","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Elimina trampas de campo","pp":15,"ppMax":15},
        {"nombre":"Ida y Vuelta","tipo":"Bicho","categoria":"Fisico","poder":70,"precision":1.0,"efecto":"Cambia al usuario","pp":20,"ppMax":20},
        {"nombre":"Plancha Corporal","tipo":"Lucha","categoria":"Fisico","poder":80,"precision":1.0,"efecto":"Usa Defensa en lugar de Ataque","pp":10,"ppMax":10},
        {"nombre":"Defensa Ferréa","tipo":"Acero","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+2 Defensa","pp":15,"ppMax":15},
        {"nombre":"Mofa","tipo":"Siniestro","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Bloquea movimientos de estado","pp":20,"ppMax":20},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10}
    ]},
    {"id":9,"nombre":"Sceptile","tipo1":"Planta","tipo2":None,"hp":70,"atk":105,"def_":65,"spe":120,
     "movimientos":[
        {"nombre":"Energibola","tipo":"Planta","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% bajar Defensa","pp":10,"ppMax":10},
        {"nombre":"Rayo Hielo","tipo":"Hielo","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% congelar","pp":10,"ppMax":10},
        {"nombre":"Foco Energía","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+2 índice crítico","pp":30,"ppMax":30},
        {"nombre":"Agilidad","tipo":"Psiquico","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+2 Velocidad","pp":30,"ppMax":30},
        {"nombre":"Hoja Aguda","tipo":"Planta","categoria":"Fisico","poder":70,"precision":1.0,"efecto":"Alto índice crítico","pp":15,"ppMax":15},
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Toxico","tipo":"Veneno","categoria":"Estado","poder":0,"precision":0.9,"efecto":"Veneno grave","pp":10,"ppMax":10}
    ]},
    {"id":10,"nombre":"Snorlax","tipo1":"Normal","tipo2":None,"hp":160,"atk":110,"def_":65,"spe":30,
     "movimientos":[
        {"nombre":"Cuerpo Pesado","tipo":"Normal","categoria":"Fisico","poder":130,"precision":1.0,"efecto":"Potencia 120 si Def > rival+15","pp":10,"ppMax":10},
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Puño Trueno","tipo":"Electrico","categoria":"Fisico","poder":75,"precision":1.0,"efecto":"10% paralizar","pp":10,"ppMax":10},
        {"nombre":"Puño Fuego","tipo":"Fuego","categoria":"Fisico","poder":75,"precision":1.0,"efecto":"10% quemar","pp":10,"ppMax":10},
        {"nombre":"Descanso","tipo":"Psiquico","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Duerme 2 turnos y recupera todo","pp":10,"ppMax":10},
        {"nombre":"Bostezo","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Duerme al siguiente turno","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Drenadoras","tipo":"Planta","categoria":"Estado","poder":0,"precision":0.9,"efecto":"Roba 1/16 de HP cada turno","pp":10,"ppMax":10}
    ]},
    {"id":11,"nombre":"Hydreigon","tipo1":"Siniestro","tipo2":"Dragon","hp":92,"atk":125,"def_":90,"spe":98,
     "movimientos":[
        {"nombre":"Cometa Draco","tipo":"Dragon","categoria":"Especial","poder":130,"precision":0.9,"efecto":"Baja mucho At. Especial","pp":5,"ppMax":5},
        {"nombre":"Pulso Umbrío","tipo":"Siniestro","categoria":"Especial","poder":80,"precision":1.0,"efecto":"20% retroceso","pp":15,"ppMax":15},
        {"nombre":"Lanzallamas","tipo":"Fuego","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% quemar","pp":15,"ppMax":15},
        {"nombre":"Malicioso","tipo":"Siniestro","categoria":"Estado","poder":0,"precision":1.0,"efecto":"-1 Defensa","pp":10,"ppMax":10},
        {"nombre":"Tierra Poderosa","tipo":"Tierra","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% bajar Defensa -2","pp":10,"ppMax":10},
        {"nombre":"Ida y Vuelta","tipo":"Bicho","categoria":"Fisico","poder":70,"precision":1.0,"efecto":"Cambia al usuario","pp":20,"ppMax":20},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Respiro","tipo":"Volador","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Recupera 50% HP","pp":10,"ppMax":10}
    ]},
    {"id":12,"nombre":"Volcarona","tipo1":"Bicho","tipo2":"Fuego","hp":85,"atk":60,"def_":65,"spe":100,
     "movimientos":[
        {"nombre":"Danza Aleteo","tipo":"Bicho","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+1 Atk, Def, Vel","pp":20,"ppMax":20},
        {"nombre":"Danza Ignea","tipo":"Fuego","categoria":"Especial","poder":80,"precision":1.0,"efecto":"50% +1 At. Especial","pp":10,"ppMax":10},
        {"nombre":"Zumbido","tipo":"Bicho","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% bajar Defensa","pp":10,"ppMax":10},
        {"nombre":"Gigadrenado","tipo":"Planta","categoria":"Especial","poder":75,"precision":1.0,"efecto":"Recupera 50% del daño","pp":10,"ppMax":10},
        {"nombre":"Psiquico","tipo":"Psiquico","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% bajar Def. Especial","pp":10,"ppMax":10},
        {"nombre":"Respiro","tipo":"Volador","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Recupera 50% HP","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10}
    ]},
    {"id":13,"nombre":"Gyarados","tipo1":"Agua","tipo2":"Volador","hp":95,"atk":125,"def_":79,"spe":81,
     "movimientos":[
        {"nombre":"Danza Dragon","tipo":"Dragon","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+1 Ataque y +1 Velocidad","pp":10,"ppMax":10},
        {"nombre":"Cascada","tipo":"Agua","categoria":"Fisico","poder":80,"precision":1.0,"efecto":"20% retroceso","pp":15,"ppMax":15},
        {"nombre":"Bote","tipo":"Volador","categoria":"Fisico","poder":85,"precision":0.85,"efecto":"Vuelo","pp":5,"ppMax":5},
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Colmillo Hielo","tipo":"Hielo","categoria":"Fisico","poder":65,"precision":0.95,"efecto":"10% congelar","pp":15,"ppMax":15},
        {"nombre":"Mofa","tipo":"Siniestro","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Bloquea movimientos de estado","pp":20,"ppMax":20},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Triturar","tipo":"Siniestro","categoria":"Fisico","poder":80,"precision":1.0,"efecto":"30% bajar Defensa","pp":15,"ppMax":15}
    ]},
    {"id":14,"nombre":"Salamence","tipo1":"Dragon","tipo2":"Volador","hp":95,"atk":135,"def_":80,"spe":100,
     "movimientos":[
        {"nombre":"Danza Dragon","tipo":"Dragon","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+1 Ataque y +1 Velocidad","pp":10,"ppMax":10},
        {"nombre":"Doble Ala","tipo":"Volador","categoria":"Fisico","poder":40,"precision":0.9,"efecto":"Golpea 2 veces","pp":10,"ppMax":10},
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Llamarada","tipo":"Fuego","categoria":"Especial","poder":110,"precision":0.85,"efecto":"10% quemar","pp":5,"ppMax":5},
        {"nombre":"Respiro","tipo":"Volador","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Recupera 50% HP","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Cometa Draco","tipo":"Dragon","categoria":"Especial","poder":130,"precision":0.9,"efecto":"Baja mucho At. Especial","pp":5,"ppMax":5},
        {"nombre":"Roca Afilada","tipo":"Roca","categoria":"Fisico","poder":100,"precision":0.8,"efecto":"Alto indice critico","pp":5,"ppMax":5}
    ]},
    {"id":15,"nombre":"Mimikyu","tipo1":"Fantasma","tipo2":"Hada","hp":55,"atk":90,"def_":80,"spe":96,
     "movimientos":[
        {"nombre":"Danza Espada","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+2 Ataque Fisico","pp":20,"ppMax":20},
        {"nombre":"Carantoña","tipo":"Hada","categoria":"Fisico","poder":90,"precision":0.9,"efecto":"10% bajar Ataque rival","pp":10,"ppMax":10},
        {"nombre":"Sombra Vil","tipo":"Fantasma","categoria":"Fisico","poder":40,"precision":1.0,"efecto":"Prioridad +1","pp":30,"ppMax":30},
        {"nombre":"Garra Sombra","tipo":"Fantasma","categoria":"Fisico","poder":70,"precision":1.0,"efecto":"Alto índice crítico","pp":15,"ppMax":15},
        {"nombre":"Puño Drenaje","tipo":"Lucha","categoria":"Fisico","poder":75,"precision":1.0,"efecto":"Recupera 50% del daño","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Mofa","tipo":"Siniestro","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Bloquea movimientos de estado","pp":20,"ppMax":20},
        {"nombre":"Fuego Fatuo","tipo":"Fuego","categoria":"Estado","poder":0,"precision":0.85,"efecto":"Quema al rival","pp":15,"ppMax":15}
    ]},
    {"id":16,"nombre":"Sylveon","tipo1":"Hada","tipo2":None,"hp":95,"atk":65,"def_":65,"spe":60,
     "movimientos":[
        {"nombre":"Vozarrón","tipo":"Normal","categoria":"Especial","poder":90,"precision":1.0,"efecto":"Ignora sustitutos","pp":10,"ppMax":10},
        {"nombre":"Paz Mental","tipo":"Psiquico","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+1 Atk y +1 Def","pp":20,"ppMax":20},
        {"nombre":"Deseo","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Cura 50% al siguiente turno","pp":10,"ppMax":10},
        {"nombre":"Proteccion","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Proteccion","pp":10,"ppMax":10},
        {"nombre":"Fuego Mistico","tipo":"Fuego","categoria":"Especial","poder":75,"precision":1.0,"efecto":"100% bajar At. Especial rival","pp":10,"ppMax":10},
        {"nombre":"Bola Sombra","tipo":"Fantasma","categoria":"Especial","poder":80,"precision":1.0,"efecto":"20% bajar Def. Especial","pp":15,"ppMax":15},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Campana Cura","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Cura todo el equipo","pp":5,"ppMax":5}
    ]},
    {"id":17,"nombre":"Mewtwo","tipo1":"Psiquico","tipo2":None,"hp":106,"atk":110,"def_":90,"spe":130,
     "movimientos":[
        {"nombre":"Psiquico","tipo":"Psiquico","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% bajar Def. Especial","pp":10,"ppMax":10},
        {"nombre":"Llamarada","tipo":"Fuego","categoria":"Especial","poder":110,"precision":0.85,"efecto":"10% quemar","pp":5,"ppMax":5},
        {"nombre":"Rayo Hielo","tipo":"Hielo","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% congelar","pp":10,"ppMax":10},
        {"nombre":"Rayo","tipo":"Electrico","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% paralizar","pp":15,"ppMax":15},
        {"nombre":"Recuperacion","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Recupera 50% HP","pp":10,"ppMax":10},
        {"nombre":"Amnesia","tipo":"Psiquico","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+2 Defensa Especial","pp":20,"ppMax":20},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Mofa","tipo":"Siniestro","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Bloquea movimientos de estado","pp":20,"ppMax":20}
    ]},
    {"id":18,"nombre":"Lucario","tipo1":"Lucha","tipo2":"Acero","hp":70,"atk":110,"def_":70,"spe":90,
     "movimientos":[
        {"nombre":"Esfera Aural","tipo":"Lucha","categoria":"Especial","poder":80,"precision":1.0,"efecto":"Nunca falla","pp":20,"ppMax":20},
        {"nombre":"Pulso Umbrio","tipo":"Siniestro","categoria":"Especial","poder":80,"precision":1.0,"efecto":"20% retroceso","pp":15,"ppMax":15},
        {"nombre":"Puño Meteoro","tipo":"Acero","categoria":"Fisico","poder":100,"precision":0.9,"efecto":"20% subir Ataque","pp":10,"ppMax":10},
        {"nombre":"Danza Espada","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+2 Ataque Fisico","pp":20,"ppMax":20},
        {"nombre":"Mofa","tipo":"Siniestro","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Bloquea movimientos de estado","pp":20,"ppMax":20},
        {"nombre":"Proteccion","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Proteccion","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Puño Bala","tipo":"Acero","categoria":"Fisico","poder":40,"precision":1.0,"efecto":"Prioridad +1","pp":10,"ppMax":10}
    ]},
    {"id":19,"nombre":"Gengar","tipo1":"Fantasma","tipo2":"Veneno","hp":60,"atk":65,"def_":60,"spe":110,
     "movimientos":[
        {"nombre":"Bola Sombra","tipo":"Fantasma","categoria":"Especial","poder":80,"precision":1.0,"efecto":"20% bajar Def. Especial","pp":15,"ppMax":15},
        {"nombre":"Bomba Lodo","tipo":"Veneno","categoria":"Especial","poder":90,"precision":1.0,"efecto":"30% envenenar","pp":10,"ppMax":10},
        {"nombre":"Foco Resplandor","tipo":"Acero","categoria":"Especial","poder":80,"precision":1.0,"efecto":"10% bajar Defensa","pp":10,"ppMax":10},
        {"nombre":"Energibola","tipo":"Planta","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% bajar Defensa","pp":10,"ppMax":10},
        {"nombre":"Destello","tipo":"Psiquico","categoria":"Especial","poder":0,"precision":1.0,"efecto":"Reduce precisión del rival","pp":10,"ppMax":10},
        {"nombre":"Hipnosis","tipo":"Psiquico","categoria":"Estado","poder":0,"precision":0.6,"efecto":"Duerme 1-3 turnos","pp":20,"ppMax":20},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Mofa","tipo":"Siniestro","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Bloquea movimientos de estado","pp":20,"ppMax":20}
    ]},
    {"id":20,"nombre":"Lapras","tipo1":"Agua","tipo2":"Hielo","hp":130,"atk":85,"def_":80,"spe":60,
     "movimientos":[
        {"nombre":"Hidrobomba","tipo":"Agua","categoria":"Especial","poder":110,"precision":0.8,"efecto":"Alto poder pero baja precision","pp":5,"ppMax":5},
        {"nombre":"Rayo Hielo","tipo":"Hielo","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% congelar","pp":10,"ppMax":10},
        {"nombre":"Rayo","tipo":"Electrico","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% paralizar","pp":15,"ppMax":15},
        {"nombre":"Canto","tipo":"Normal","categoria":"Estado","poder":0,"precision":0.55,"efecto":"Duerme 2-5 turnos","pp":15,"ppMax":15},
        {"nombre":"Resonancia","tipo":"Hielo","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+2 Defensa a todos enemigos","pp":5,"ppMax":5},
        {"nombre":"Proteccion","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Proteccion","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Descanso","tipo":"Psiquico","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Duerme 2 turnos y recupera todo","pp":10,"ppMax":10}
    ]},
    {"id":21,"nombre":"Dragonite","tipo1":"Dragon","tipo2":"Volador","hp":91,"atk":134,"def_":95,"spe":80,
     "movimientos":[
        {"nombre":"Danza Dragon","tipo":"Dragon","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+1 Ataque y +1 Velocidad","pp":10,"ppMax":10},
        {"nombre":"Velocidad Extrema","tipo":"Normal","categoria":"Fisico","poder":80,"precision":1.0,"efecto":"Prioridad +2","pp":5,"ppMax":5},
        {"nombre":"Doble Ala","tipo":"Volador","categoria":"Fisico","poder":40,"precision":0.9,"efecto":"Golpea 2 veces","pp":10,"ppMax":10},
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Puño Fuego","tipo":"Fuego","categoria":"Fisico","poder":75,"precision":1.0,"efecto":"10% quemar","pp":10,"ppMax":10},
        {"nombre":"Respiro","tipo":"Volador","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Recupera 50% HP","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Giro Hielo","tipo":"Hielo","categoria":"Fisico","poder":80,"precision":1.0,"efecto":"Elimina terreno activo","pp":15,"ppMax":15}
    ]},
    {"id":22,"nombre":"Alakazam","tipo1":"Psiquico","tipo2":None,"hp":55,"atk":50,"def_":45,"spe":120,
     "movimientos":[
        {"nombre":"Psiquico","tipo":"Psiquico","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% bajar Def. Especial","pp":10,"ppMax":10},
        {"nombre":"Foco Resplandor","tipo":"Acero","categoria":"Especial","poder":80,"precision":1.0,"efecto":"10% bajar Defensa","pp":10,"ppMax":10},
        {"nombre":"Energibola","tipo":"Planta","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% bajar Defensa","pp":10,"ppMax":10},
        {"nombre":"Onda Trueno","tipo":"Electrico","categoria":"Estado","poder":0,"precision":0.9,"efecto":"Paraliza al rival","pp":20,"ppMax":20},
        {"nombre":"Recuperacion","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Recupera 50% HP","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Mofa","tipo":"Siniestro","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Bloquea movimientos de estado","pp":20,"ppMax":20},
        {"nombre":"Foco Energía","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+2 índice crítico","pp":30,"ppMax":30}
    ]},
    {"id":23,"nombre":"Venusaur","tipo1":"Planta","tipo2":"Veneno","hp":80,"atk":82,"def_":83,"spe":80,
     "movimientos":[
        {"nombre":"Energibola","tipo":"Planta","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% bajar Defensa","pp":10,"ppMax":10},
        {"nombre":"Bomba Lodo","tipo":"Veneno","categoria":"Especial","poder":90,"precision":1.0,"efecto":"30% envenenar","pp":10,"ppMax":10},
        {"nombre":"Síntesis","tipo":"Planta","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Recupera 25% HP","pp":5,"ppMax":5},
        {"nombre":"Polvo Veneno","tipo":"Veneno","categoria":"Estado","poder":0,"precision":0.75,"efecto":"Envenena","pp":35,"ppMax":35},
        {"nombre":"Drenadoras","tipo":"Planta","categoria":"Estado","poder":0,"precision":0.9,"efecto":"Roba 1/16 de HP cada turno","pp":10,"ppMax":10},
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Proteccion","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Proteccion","pp":10,"ppMax":10}
    ]},
    {"id":24,"nombre":"Groudon","tipo1":"Tierra","tipo2":None,"hp":100,"atk":150,"def_":140,"spe":90,
     "movimientos":[
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Puño Fuego","tipo":"Fuego","categoria":"Fisico","poder":75,"precision":1.0,"efecto":"10% quemar","pp":10,"ppMax":10},
        {"nombre":"Roca Afilada","tipo":"Roca","categoria":"Fisico","poder":100,"precision":0.8,"efecto":"Alto indice critico","pp":5,"ppMax":5},
        {"nombre":"Danza Dragon","tipo":"Dragon","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+1 Ataque y +1 Velocidad","pp":10,"ppMax":10},
        {"nombre":"Cuchillada","tipo":"Normal","categoria":"Fisico","poder":70,"precision":1.0,"efecto":"Alto indice critico","pp":20,"ppMax":20},
        {"nombre":"Mofa","tipo":"Siniestro","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Bloquea movimientos de estado","pp":20,"ppMax":20},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Toxico","tipo":"Veneno","categoria":"Estado","poder":0,"precision":0.9,"efecto":"Veneno grave","pp":10,"ppMax":10}
    ]},
    {"id":25,"nombre":"Pikachu","tipo1":"Electrico","tipo2":None,"hp":35,"atk":55,"def_":40,"spe":90,
     "movimientos":[
        {"nombre":"Rayo","tipo":"Electrico","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% paralizar","pp":15,"ppMax":15},
        {"nombre":"Voltio Cambio","tipo":"Electrico","categoria":"Especial","poder":70,"precision":1.0,"efecto":"Cambia al usuario después de atacar","pp":20,"ppMax":20},
        {"nombre":"Onda Trueno","tipo":"Electrico","categoria":"Estado","poder":0,"precision":0.9,"efecto":"Paraliza al rival","pp":20,"ppMax":20},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Destello","tipo":"Psiquico","categoria":"Especial","poder":0,"precision":1.0,"efecto":"Reduce precisión","pp":10,"ppMax":10},
        {"nombre":"Doble Equipo","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+2 Evasión","pp":15,"ppMax":15},
        {"nombre":"Enfado","tipo":"Dragon","categoria":"Fisico","poder":120,"precision":1.0,"efecto":"2-3 turnos luego confunde","pp":10,"ppMax":10},
        {"nombre":"Mofa","tipo":"Siniestro","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Bloquea movimientos de estado","pp":20,"ppMax":20}
    ]},
    {"id":26,"nombre":"Blastoise","tipo1":"Agua","tipo2":None,"hp":79,"atk":83,"def_":100,"spe":78,
     "movimientos":[
        {"nombre":"Hidrobomba","tipo":"Agua","categoria":"Especial","poder":110,"precision":0.8,"efecto":"Alto poder pero baja precision","pp":5,"ppMax":5},
        {"nombre":"Rayo Hielo","tipo":"Hielo","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% congelar","pp":10,"ppMax":10},
        {"nombre":"Onda Trueno","tipo":"Electrico","categoria":"Estado","poder":0,"precision":0.9,"efecto":"Paraliza al rival","pp":20,"ppMax":20},
        {"nombre":"Respiro","tipo":"Volador","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Recupera 50% HP","pp":10,"ppMax":10},
        {"nombre":"Cascada","tipo":"Agua","categoria":"Fisico","poder":80,"precision":1.0,"efecto":"20% retroceso","pp":15,"ppMax":15},
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Mofa","tipo":"Siniestro","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Bloquea movimientos de estado","pp":20,"ppMax":20}
    ]},
    {"id":27,"nombre":"Haxorus","tipo1":"Dragon","tipo2":None,"hp":76,"atk":147,"def_":90,"spe":97,
     "movimientos":[
        {"nombre":"Danza Dragon","tipo":"Dragon","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+1 Ataque y +1 Velocidad","pp":10,"ppMax":10},
        {"nombre":"Enfado","tipo":"Dragon","categoria":"Fisico","poder":120,"precision":1.0,"efecto":"2-3 turnos luego confunde","pp":10,"ppMax":10},
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Puya Nociva","tipo":"Veneno","categoria":"Fisico","poder":80,"precision":1.0,"efecto":"30% envenenar","pp":20,"ppMax":20},
        {"nombre":"A Bocajarro","tipo":"Lucha","categoria":"Fisico","poder":120,"precision":1.0,"efecto":"Baja Defensa y Defensa Especial","pp":5,"ppMax":5},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Danza Espada","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+2 Ataque Fisico","pp":20,"ppMax":20},
        {"nombre":"Mofa","tipo":"Siniestro","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Bloquea movimientos de estado","pp":20,"ppMax":20}
    ]},
    {"id":28,"nombre":"Charizard","tipo1":"Fuego","tipo2":"Volador","hp":78,"atk":84,"def_":78,"spe":100,
     "movimientos":[
        {"nombre":"Llamarada","tipo":"Fuego","categoria":"Especial","poder":110,"precision":0.85,"efecto":"10% quemar","pp":5,"ppMax":5},
        {"nombre":"Tajo Aereo","tipo":"Volador","categoria":"Especial","poder":75,"precision":0.95,"efecto":"30% retroceso","pp":15,"ppMax":15},
        {"nombre":"Terremoto","tipo":"Tierra","categoria":"Fisico","poder":100,"precision":1.0,"efecto":"Golpea a todos","pp":10,"ppMax":10},
        {"nombre":"Danza Dragon","tipo":"Dragon","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+1 Ataque y +1 Velocidad","pp":10,"ppMax":10},
        {"nombre":"Respiro","tipo":"Volador","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Recupera 50% HP","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Mofa","tipo":"Siniestro","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Bloquea movimientos de estado","pp":20,"ppMax":20},
        {"nombre":"Calcinacion","tipo":"Fuego","categoria":"Estado","poder":30,"precision":0.85,"efecto":"Quema al rival","pp":15,"ppMax":15}
    ]},
    {"id":29,"nombre":"Kyogre","tipo1":"Agua","tipo2":None,"hp":100,"atk":100,"def_":90,"spe":90,
     "movimientos":[
        {"nombre":"Surf","tipo":"Agua","categoria":"Especial","poder":90,"precision":1.0,"efecto":"Golpea a todos los rivales","pp":15,"ppMax":15},
        {"nombre":"Rayo Hielo","tipo":"Hielo","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% congelar","pp":10,"ppMax":10},
        {"nombre":"Trueno","tipo":"Electrico","categoria":"Especial","poder":110,"precision":0.7,"efecto":"30% paralizar","pp":10,"ppMax":10},
        {"nombre":"Calma Mental","tipo":"Psiquico","categoria":"Estado","poder":0,"precision":1.0,"efecto":"+2 AtEsp","pp":10,"ppMax":10},
        {"nombre":"Pulso Origen","tipo":"Agua","categoria":"Especial","poder":110,"precision":0.85,"efecto":"Poderoso ataque de agua","pp":10,"ppMax":10},
        {"nombre":"Respiro","tipo":"Volador","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Recupera 50% HP","pp":10,"ppMax":10},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10},
        {"nombre":"Toxico","tipo":"Veneno","categoria":"Estado","poder":0,"precision":0.9,"efecto":"Veneno grave","pp":10,"ppMax":10}
    ]},
    {"id":30,"nombre":"Greninja","tipo1":"Agua","tipo2":"Siniestro","hp":72,"atk":95,"def_":67,"spe":122,
     "movimientos":[
        {"nombre":"Hidrobomba","tipo":"Agua","categoria":"Especial","poder":110,"precision":0.8,"efecto":"Alto poder pero baja precision","pp":5,"ppMax":5},
        {"nombre":"Rayo Hielo","tipo":"Hielo","categoria":"Especial","poder":90,"precision":1.0,"efecto":"10% congelar","pp":10,"ppMax":10},
        {"nombre":"Pulso Umbrío","tipo":"Siniestro","categoria":"Especial","poder":80,"precision":1.0,"efecto":"20% retroceso","pp":15,"ppMax":15},
        {"nombre":"Ida y Vuelta","tipo":"Bicho","categoria":"Fisico","poder":70,"precision":1.0,"efecto":"Cambia al usuario","pp":20,"ppMax":20},
        {"nombre":"Puas","tipo":"Tierra","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Daño al cambiar rival","pp":20,"ppMax":20},
        {"nombre":"Puas Toxicas","tipo":"Veneno","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Daño al cambiar rival","pp":20,"ppMax":20},
        {"nombre":"Fuerza Psíquica","tipo":"Psiquico","categoria":"Especial","poder":80,"precision":1.0,"efecto":"Sin efecto adicional","pp":20,"ppMax":20},
        {"nombre":"Sustituto","tipo":"Normal","categoria":"Estado","poder":0,"precision":1.0,"efecto":"Crea un sustituto con 1/4 de HP","pp":10,"ppMax":10}
    ]}
]